"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth-user";
import { leadIdSchema, leadSchema, type ActionState } from "@/lib/validation";

function values(formData: FormData) { return { name: formData.get("name"), email: formData.get("email"), phone: formData.get("phone"), company: formData.get("company"), source: formData.get("source"), status: formData.get("status"), message: formData.get("message"), estimatedValue: formData.get("estimatedValue"), nextFollowUpDate: formData.get("nextFollowUpDate") }; }
export async function createLeadAction(_state: ActionState, formData: FormData): Promise<ActionState> { const user = await requireUser(); const parsed = leadSchema.safeParse(values(formData)); if (!parsed.success) return { errors: parsed.error.flatten().fieldErrors, message: "Please correct the highlighted fields." }; let id: string; try { const lead = await prisma.lead.create({ data: { ...parsed.data, userId: user.id } }); id = lead.id; } catch { return { message: "We couldn't save this lead. Please try again." }; } revalidatePath("/"); revalidatePath("/leads"); redirect(`/leads/${id}`); }
export async function updateLeadAction(id: string, _state: ActionState, formData: FormData): Promise<ActionState> { const user = await requireUser(); const validId = leadIdSchema.safeParse(id); const parsed = leadSchema.safeParse(values(formData)); if (!validId.success || !parsed.success) return { errors: parsed.success ? undefined : parsed.error.flatten().fieldErrors, message: "Please correct the highlighted fields." }; const owned = await prisma.lead.findFirst({ where: { id, userId: user.id }, select: { id: true } }); if (!owned) return { message: "Lead not found." }; try { await prisma.lead.update({ where: { id }, data: parsed.data }); } catch { return { message: "We couldn't update this lead. Please try again." }; } revalidatePath("/"); revalidatePath("/leads"); revalidatePath(`/leads/${id}`); return { success: true, message: "Lead updated." }; }
export async function changeLeadStatusAction(id: string, formData: FormData) { const user = await requireUser(); const parsedId = leadIdSchema.safeParse(id); const parsed = leadSchema.pick({ status: true }).safeParse({ status: formData.get("status") }); if (!parsedId.success || !parsed.success) return; await prisma.lead.updateMany({ where: { id, userId: user.id }, data: { status: parsed.data.status } }); revalidatePath("/"); revalidatePath("/leads"); revalidatePath(`/leads/${id}`); }
export async function deleteLeadAction(id: string) { const user = await requireUser(); const parsed = leadIdSchema.safeParse(id); if (!parsed.success) return; await prisma.lead.deleteMany({ where: { id, userId: user.id } }); revalidatePath("/"); revalidatePath("/leads"); redirect("/leads"); }
